# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

java_version=25
minecraft_version=26.2

mod_id=snapyaw
mod_name=SnapYaw
mod_license=MIT
mod_version=0.1.0
mod_group_id=lol.hub.snapyaw
mod_authors=hub
mod_description=Stop falling off your bridges! Snap your yaw to the nearest cardinal direction.
